export class Returndeliverynote{
    id: number;
    rdcrequestno: string;
    requestedby: string;
    requesteddepartment: string;
    customerid: string;
    customername: string;
    supplierid: string;
    suppliername: string;
    itemcode: string;
    itemname: string;
    itemtype: string;
    lotno: string;
    batchno: string;
    returnitemcode: string;
    returnitemname: string;
    returnitemtype: string;
    returnlotno: string;
    returnbatchno: string;
    grnno: string;
    invoiceno: string;
    salesorderno: string;
    hsncode: string;
    quantity: number;
    uom: number;
    unitprice: number;
    totalprice: number;
    originatingCity: string;
    destinationCity: string;
    fromaddress: string;
    toaddress : string;
    pickuplocation : string;
    destinationlocation : string;
    returndate: Date;
    returnindays: string;
    returnedby: string;
    returnreason: string;
    status: string;
    createdby: string;
    updatedby: string;
    createdAt: Date;
    updatedAt : Date;
}
